monolog:
    channels:
        - deprecation # logged in the dedicated channel when attributed to a handler
        - webpush # logged in the dedicated channel when attributed to a handler
        - messenger_audit # NB: 'messenger' is already a channel for core messenger logs
        - cron # logged in the dedicated channel when attributed to a handler
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            webpush:
                type: rotating_file
                channels: ['webpush']
                path: '%kernel.logs_dir%/webpush.%kernel.environment%.log'
                max_files: 7
                level: info
            messenger_audit:
                type: rotating_file
                channels: ['messenger_audit']
                path: '%kernel.logs_dir%/messenger_audit.%kernel.environment%.log'
                max_files: 7
                level: info

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 7
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            # uncomment to log deprecations in prod and staging
            # deprecation:
            #     type: rotating_file
            #     channels: [deprecation]
            #     path: "%kernel.logs_dir%/deprecation.%kernel.environment%.log"
            #     max_files: 7
            cron:
                type: rotating_file
                channels: ['cron']
                path: '%kernel.logs_dir%/cron.%kernel.environment%.log'
                max_files: 7
                level: info
