symfonycasts_reset_password:
    request_password_repository: Pack\Security\Repository\ResetPasswordRequestRepository
    # password request expiration
    lifetime: 3600
    # minimum allowed time between password requests
    throttle_limit: 600
    enable_garbage_collection: true
