framework:
    default_locale: '%default_locale%'
    enabled_locales: '%locales%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        # additional paths
        paths:
            - '%kernel.project_dir%/src/Pack/Security/translations'
        fallbacks: ['%default_locale%']
