twig:
    file_name_pattern: '*.twig'
    
    default_path: '%kernel.project_dir%/templates'
    paths:
        src/Twig/Component: 'component'
        pack/Security/templates: 'security'
        pack/Status/templates: 'status'
        admin/templates: 'admin'

    form_themes:
        - 'form/form_theme.html.twig'
    
    # twig globals can be added here or in App\Twig\SiteExtension
    globals:
        default_locale: '%default_locale%'
        locales: '%locales%'

    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    # deprecated. use "error_controller" under "framework" instead
    exception_controller: null

when@test:
    twig:
        strict_variables: true
