ux_icons:
    aliases:
        theme: 'ix:light-dark'
        home: 'ph:house'
        back: 'ic:round-arrow-back-ios'
        forward: 'ic:round-arrow-forward-ios'
        trash: 'lucide:trash-2'
        account: 'qlementine-icons:user-16'
        external-link: 'prime:external-link'
        info: 'lucide:info'
        settings: 'lucide:settings'
        filter: 'mage:filter'
        grab-horizontal: 'charm:grab-horizontal'
        grab-vertical: 'charm:grab-vertical'
        received: 'bi:check'
        read: 'bi:check-all'
        chat: 'gridicons:chat'
        message: 'gridicons:chat'
        emoji: 'fluent:emoji-add-20-regular'
        dots: 'tabler:dots-vertical'
        add: 'ic:baseline-add'
        new: 'ic:baseline-add'
        show: 'ic:baseline-remove-red-eye'
        edit: 'ic:baseline-edit'
        delete: 'ic:baseline-delete'
        archive: 'ic:baseline-archive'
        unarchive: 'ic:baseline-unarchive'
        login: 'material-symbols:login'
        logout: 'material-symbols:logout'
