ux_icons:
    aliases:
        theme: 'ix:light-dark'
        home: 'ph:house'
        back: 'ic:round-arrow-back-ios'
        forward: 'ic:round-arrow-forward-ios'
        trash: 'lucide:trash-2'
        account: 'qlementine-icons:user-16'
        external-link: 'prime:external-link'
        info: 'lucide:info'
        settings: 'lucide:settings'
        filter: 'mage:filter'
        grab-horizontal: 'charm:grab-horizontal'
        grab-vertical: 'charm:grab-vertical'
        received: 'bi:check'
        read: 'bi:check-all'
        chat: 'gridicons:chat'
        message: 'gridicons:chat'
        emoji: 'fluent:emoji-add-20-regular'
        dots: 'tabler:dots-vertical'
        add: 'ic:baseline-add'
        new: 'ic:baseline-add'
        show: 'ic:baseline-remove-red-eye'
        edit: 'ic:baseline-edit'
        refresh: 'ion:refresh'
        # delete: 'ic:baseline-delete'
        delete: 'material-symbols:delete-outline'
        archive: 'ic:baseline-archive'
        unarchive: 'ic:baseline-unarchive'
        login: 'material-symbols:login'
        logout: 'material-symbols:logout'
        calendar: 'bx:calendar'
        trophy: 'bx:trophy'
        bracket: 'mdi:bracket'
        medal: 'fa-solid:medal'
        interclubs: 'fluent:people-team-28-regular'
        lessons: 'mdi:tennis'
        practical-infos: 'mdi:information-outline'
        confirm-user: 'streamline-block:basic-ui-confirm-user'
        check: 'mingcute:check-fill'
        cross: 'maki:cross'
