<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Tous les comptes existants sont à inviter comme ceux créés par un admin (PlayerAccountManager) :
 * rôle ROLE_AUTOGENERATED_PASSWORD, retiré quand la personne choisit son mot de passe.
 * Décision du 2026-09-25 : tous les comptes, y compris ceux des admins.
 */
final class Version20260925190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'ROLE_AUTOGENERATED_PASSWORD sur tous les comptes existants';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            UPDATE user_
            SET roles = (roles::jsonb || '["ROLE_AUTOGENERATED_PASSWORD"]'::jsonb)::json
            WHERE NOT roles::jsonb @> '["ROLE_AUTOGENERATED_PASSWORD"]'::jsonb
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            UPDATE user_
            SET roles = (roles::jsonb - 'ROLE_AUTOGENERATED_PASSWORD')::json
        SQL);
    }
}
