<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250904143755 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE date (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE "group" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE group_player (group_id INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY(group_id, player_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_4B9FA2B5FE54D947 ON group_player (group_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_4B9FA2B599E6F5DF ON group_player (player_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE interfac_match (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, player_group_id INT NOT NULL, timeslot_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_3B918C5DF88398A7 ON interfac_match (player_group_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_3B918C5DF920B9E9 ON interfac_match (timeslot_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE interfac_match_player (interfac_match_id INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY(interfac_match_id, player_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8116B032121B0C7D ON interfac_match_player (interfac_match_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8116B03299E6F5DF ON interfac_match_player (player_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) DEFAULT NULL, ranking VARCHAR(255) DEFAULT NULL, gender VARCHAR(255) NOT NULL, birthyear VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE test_message_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message_id VARCHAR(255) DEFAULT NULL, message_created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, message_processed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE time (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, time TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE time_slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_id INT NOT NULL, time_id INT NOT NULL, end_time_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1B3294AB897366B ON time_slot (date_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1B3294A5EEADD3B ON time_slot (time_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1B3294ACB258CD2 ON time_slot (end_time_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE user_ (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, last_login TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, verified BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, closed BOOLEAN NOT NULL, locked BOOLEAN NOT NULL, hellbanned BOOLEAN NOT NULL, scam BOOLEAN DEFAULT NULL, demarchage BOOLEAN DEFAULT NULL, safe BOOLEAN DEFAULT false NOT NULL, watchlist BOOLEAN NOT NULL, whitelist BOOLEAN NOT NULL, admin_reviewed BOOLEAN NOT NULL, kotcop_score DOUBLE PRECISION DEFAULT NULL, kotcop_updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON user_ (email)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE group_player ADD CONSTRAINT FK_4B9FA2B5FE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE group_player ADD CONSTRAINT FK_4B9FA2B599E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE interfac_match ADD CONSTRAINT FK_3B918C5DF88398A7 FOREIGN KEY (player_group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE interfac_match ADD CONSTRAINT FK_3B918C5DF920B9E9 FOREIGN KEY (timeslot_id) REFERENCES time_slot (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE interfac_match_player ADD CONSTRAINT FK_8116B032121B0C7D FOREIGN KEY (interfac_match_id) REFERENCES interfac_match (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE interfac_match_player ADD CONSTRAINT FK_8116B03299E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES user_ (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE time_slot ADD CONSTRAINT FK_1B3294AB897366B FOREIGN KEY (date_id) REFERENCES date (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE time_slot ADD CONSTRAINT FK_1B3294A5EEADD3B FOREIGN KEY (time_id) REFERENCES time (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE time_slot ADD CONSTRAINT FK_1B3294ACB258CD2 FOREIGN KEY (end_time_id) REFERENCES time (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE group_player DROP CONSTRAINT FK_4B9FA2B5FE54D947
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE group_player DROP CONSTRAINT FK_4B9FA2B599E6F5DF
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE interfac_match DROP CONSTRAINT FK_3B918C5DF88398A7
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE interfac_match DROP CONSTRAINT FK_3B918C5DF920B9E9
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE interfac_match_player DROP CONSTRAINT FK_8116B032121B0C7D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE interfac_match_player DROP CONSTRAINT FK_8116B03299E6F5DF
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE time_slot DROP CONSTRAINT FK_1B3294AB897366B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE time_slot DROP CONSTRAINT FK_1B3294A5EEADD3B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE time_slot DROP CONSTRAINT FK_1B3294ACB258CD2
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE date
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE "group"
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE group_player
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE interfac_match
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE interfac_match_player
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE player
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE reset_password_request
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE test_message_log
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE time
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE time_slot
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE user_
        SQL);
    }
}
