<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251019154416 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE participant_confirmation_info (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_email_sent BOOLEAN NOT NULL, is_confirmed_by_admin BOOLEAN NOT NULL, confirmed_by_admin_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_confirmed_by_player BOOLEAN NOT NULL, confirmed_by_player_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, participant_id INT NOT NULL, admin_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B86A88DF9D1C3019 ON participant_confirmation_info (participant_id)');
        $this->addSql('CREATE INDEX IDX_B86A88DF642B8210 ON participant_confirmation_info (admin_id)');
        $this->addSql('ALTER TABLE participant_confirmation_info ADD CONSTRAINT FK_B86A88DF9D1C3019 FOREIGN KEY (participant_id) REFERENCES match_participant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant_confirmation_info ADD CONSTRAINT FK_B86A88DF642B8210 FOREIGN KEY (admin_id) REFERENCES user_ (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE participant_confirmation_info DROP CONSTRAINT FK_B86A88DF9D1C3019');
        $this->addSql('ALTER TABLE participant_confirmation_info DROP CONSTRAINT FK_B86A88DF642B8210');
        $this->addSql('DROP TABLE participant_confirmation_info');
    }
}
