<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250905132256 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, slot_id INT NOT NULL, match_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDE59E5119C ON booking (slot_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDE2ABEACD6 ON booking (match_id)');
        $this->addSql('CREATE TABLE court (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE date (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "group" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE group_player (group_id INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY (group_id, player_id))');
        $this->addSql('CREATE INDEX IDX_4B9FA2B5FE54D947 ON group_player (group_id)');
        $this->addSql('CREATE INDEX IDX_4B9FA2B599E6F5DF ON group_player (player_id)');
        $this->addSql('CREATE TABLE interfac_match (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3B918C5DFE54D947 ON interfac_match (group_id)');
        $this->addSql('CREATE TABLE interfac_match_player (interfac_match_id INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY (interfac_match_id, player_id))');
        $this->addSql('CREATE INDEX IDX_8116B032121B0C7D ON interfac_match_player (interfac_match_id)');
        $this->addSql('CREATE INDEX IDX_8116B03299E6F5DF ON interfac_match_player (player_id)');
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) DEFAULT NULL, ranking VARCHAR(255) DEFAULT NULL, gender VARCHAR(255) NOT NULL, birthyear VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, starts_at TIME(0) WITHOUT TIME ZONE NOT NULL, ends_at TIME(0) WITHOUT TIME ZONE NOT NULL, date_id INT NOT NULL, court_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC0E2067B897366B ON slot (date_id)');
        $this->addSql('CREATE INDEX IDX_AC0E2067E3184009 ON slot (court_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_DATE_AND_START ON slot (date_id, starts_at)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_DATE_AND_END ON slot (date_id, ends_at)');
        $this->addSql('CREATE TABLE test_message_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message_id VARCHAR(255) DEFAULT NULL, message_created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, message_processed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_ (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, last_login TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, verified BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, closed BOOLEAN NOT NULL, locked BOOLEAN NOT NULL, hellbanned BOOLEAN NOT NULL, scam BOOLEAN DEFAULT NULL, demarchage BOOLEAN DEFAULT NULL, safe BOOLEAN DEFAULT false NOT NULL, watchlist BOOLEAN NOT NULL, whitelist BOOLEAN NOT NULL, admin_reviewed BOOLEAN NOT NULL, kotcop_score DOUBLE PRECISION DEFAULT NULL, kotcop_updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON user_ (email)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE59E5119C FOREIGN KEY (slot_id) REFERENCES slot (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE2ABEACD6 FOREIGN KEY (match_id) REFERENCES interfac_match (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE group_player ADD CONSTRAINT FK_4B9FA2B5FE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_player ADD CONSTRAINT FK_4B9FA2B599E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interfac_match ADD CONSTRAINT FK_3B918C5DFE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE interfac_match_player ADD CONSTRAINT FK_8116B032121B0C7D FOREIGN KEY (interfac_match_id) REFERENCES interfac_match (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE interfac_match_player ADD CONSTRAINT FK_8116B03299E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES user_ (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE slot ADD CONSTRAINT FK_AC0E2067B897366B FOREIGN KEY (date_id) REFERENCES date (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE slot ADD CONSTRAINT FK_AC0E2067E3184009 FOREIGN KEY (court_id) REFERENCES court (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE59E5119C');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE2ABEACD6');
        $this->addSql('ALTER TABLE group_player DROP CONSTRAINT FK_4B9FA2B5FE54D947');
        $this->addSql('ALTER TABLE group_player DROP CONSTRAINT FK_4B9FA2B599E6F5DF');
        $this->addSql('ALTER TABLE interfac_match DROP CONSTRAINT FK_3B918C5DFE54D947');
        $this->addSql('ALTER TABLE interfac_match_player DROP CONSTRAINT FK_8116B032121B0C7D');
        $this->addSql('ALTER TABLE interfac_match_player DROP CONSTRAINT FK_8116B03299E6F5DF');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE slot DROP CONSTRAINT FK_AC0E2067B897366B');
        $this->addSql('ALTER TABLE slot DROP CONSTRAINT FK_AC0E2067E3184009');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE court');
        $this->addSql('DROP TABLE date');
        $this->addSql('DROP TABLE "group"');
        $this->addSql('DROP TABLE group_player');
        $this->addSql('DROP TABLE interfac_match');
        $this->addSql('DROP TABLE interfac_match_player');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE slot');
        $this->addSql('DROP TABLE test_message_log');
        $this->addSql('DROP TABLE user_');
    }
}
