<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Enum\Ranking;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Saisons
 *
 * - season : Été YYYY / Hiver YYYY-ZZZZ
 * - group.season_id : une poule (et donc ses matchs) appartient à une saison
 * - player_season : inscription d'un joueur pour une saison (classement, interfacs, interclubs, cours)
 *
 * Données existantes : tout est rattaché à la saison "Hiver 2025-2026", qui devient la saison courante.
 * Le classement et les activités des joueurs sont copiés dans leur inscription pour cette saison
 * AVANT la suppression des colonnes de la table player.
 */
final class Version20260919174049 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Saisons : season, group.season_id, player_season (données existantes => Hiver 2025-2026)';
    }

    public function up(Schema $schema): void
    {
        // Schema
        $this->addSql('CREATE TABLE season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, year SMALLINT NOT NULL, starts_on DATE NOT NULL, ends_on DATE NOT NULL, is_current BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX season_type_year_unique ON season (type, year)');
        $this->addSql('CREATE TABLE player_season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ranking VARCHAR(255) DEFAULT NULL, ranking_order SMALLINT DEFAULT NULL, interfacs BOOLEAN DEFAULT NULL, interclubs BOOLEAN DEFAULT NULL, cours BOOLEAN DEFAULT NULL, confirmed BOOLEAN DEFAULT true NOT NULL, player_id INT NOT NULL, season_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FE4CD7799E6F5DF ON player_season (player_id)');
        $this->addSql('CREATE INDEX IDX_6FE4CD774EC001D1 ON player_season (season_id)');
        $this->addSql('CREATE UNIQUE INDEX player_season_unique ON player_season (player_id, season_id)');
        $this->addSql('ALTER TABLE player_season ADD CONSTRAINT FK_6FE4CD7799E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player_season ADD CONSTRAINT FK_6FE4CD774EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');

        // Data: saison Hiver 2025-2026 = saison courante
        $this->addSql("INSERT INTO season (type, year, starts_on, ends_on, is_current) VALUES ('hiver', 2025, '2025-11-01', '2026-03-31', true)");

        // Data: inscriptions des joueurs existants (confirmées)
        $this->addSql("
            INSERT INTO player_season (player_id, season_id, ranking, ranking_order, interfacs, interclubs, cours, confirmed)
            SELECT p.id, s.id, p.ranking, p.ranking_order, p.interfacs, p.interclubs, p.cours, true
            FROM player p, season s
            WHERE s.type = 'hiver' AND s.year = 2025
        ");

        // Data: ranking_order manquait pour certains joueurs => recalcul (cf PlayerSeason::setRanking())
        $cases = '';
        foreach (Ranking::cases() as $order => $ranking) {
            $cases .= sprintf(' WHEN %s THEN %d', $this->connection->quote($ranking->value), $order);
        }
        $this->addSql('UPDATE player_season SET ranking_order = CASE ranking' . $cases . ' ELSE NULL END WHERE ranking IS NOT NULL');

        // Poules existantes => Hiver 2025-2026
        $this->addSql('ALTER TABLE "group" ADD season_id INT DEFAULT NULL');
        $this->addSql("UPDATE \"group\" SET season_id = (SELECT id FROM season WHERE type = 'hiver' AND year = 2025)");
        $this->addSql('ALTER TABLE "group" ALTER season_id SET NOT NULL');
        $this->addSql('ALTER TABLE "group" ALTER season_id DROP DEFAULT');
        $this->addSql('ALTER TABLE "group" ADD CONSTRAINT FK_6DC044C54EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_6DC044C54EC001D1 ON "group" (season_id)');

        // Les données par saison quittent la table player (copiées ci-dessus)
        $this->addSql('ALTER TABLE player DROP ranking');
        $this->addSql('ALTER TABLE player DROP ranking_order');
        $this->addSql('ALTER TABLE player DROP interfacs');
        $this->addSql('ALTER TABLE player DROP interclubs');
        $this->addSql('ALTER TABLE player DROP cours');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE player ADD ranking VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE player ADD ranking_order SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE player ADD interfacs BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE player ADD interclubs BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE player ADD cours BOOLEAN DEFAULT NULL');

        // Data: on récupère les données de la saison courante.
        // NB: l'historique des autres saisons est perdu.
        $this->addSql('
            UPDATE player p
            SET ranking = ps.ranking, ranking_order = ps.ranking_order, interfacs = ps.interfacs, interclubs = ps.interclubs, cours = ps.cours
            FROM player_season ps
            INNER JOIN season s ON s.id = ps.season_id AND s.is_current = true
            WHERE ps.player_id = p.id
        ');

        $this->addSql('ALTER TABLE "group" DROP CONSTRAINT FK_6DC044C54EC001D1');
        $this->addSql('DROP INDEX IDX_6DC044C54EC001D1');
        $this->addSql('ALTER TABLE "group" DROP season_id');
        $this->addSql('ALTER TABLE player_season DROP CONSTRAINT FK_6FE4CD7799E6F5DF');
        $this->addSql('ALTER TABLE player_season DROP CONSTRAINT FK_6FE4CD774EC001D1');
        $this->addSql('DROP TABLE player_season');
        $this->addSql('DROP TABLE season');
    }
}
