<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251012155201 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE match_participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, side VARCHAR(255) NOT NULL, match_id INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E5061A392ABEACD6 ON match_participant (match_id)');
        $this->addSql('CREATE INDEX IDX_E5061A3999E6F5DF ON match_participant (player_id)');
        $this->addSql('ALTER TABLE match_participant ADD CONSTRAINT FK_E5061A392ABEACD6 FOREIGN KEY (match_id) REFERENCES interfac_match (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE match_participant ADD CONSTRAINT FK_E5061A3999E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE match_participant DROP CONSTRAINT FK_E5061A392ABEACD6');
        $this->addSql('ALTER TABLE match_participant DROP CONSTRAINT FK_E5061A3999E6F5DF');
        $this->addSql('DROP TABLE match_participant');
    }
}
