<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251012200336 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE match_result (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, set1_a SMALLINT DEFAULT NULL, set1_b SMALLINT DEFAULT NULL, set2_a SMALLINT DEFAULT NULL, set2_b SMALLINT DEFAULT NULL, set3_a SMALLINT DEFAULT NULL, set3_b SMALLINT DEFAULT NULL, points_a SMALLINT DEFAULT NULL, points_b SMALLINT DEFAULT NULL, match_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B20538122ABEACD6 ON match_result (match_id)');
        $this->addSql('ALTER TABLE match_result ADD CONSTRAINT FK_B20538122ABEACD6 FOREIGN KEY (match_id) REFERENCES interfac_match (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE match_result DROP CONSTRAINT FK_B20538122ABEACD6');
        $this->addSql('DROP TABLE match_result');
    }
}
