<?php

namespace App\Controller\AccountArea;

use App\Controller\BaseController;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Pack\Security\Form\ChangePasswordForm;
use Pack\Security\LoginFormAuthenticator;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

/**
 * Choisir son mot de passe, pour une personne connectée dont un admin a créé le compte
 * (PlayerAccountManager, ROLE_AUTOGENERATED_PASSWORD) : destination du lien d'invitation (Admin\Mailer\InvitationMailer)
 * et de la bannière affichée tant que le mot de passe n'est pas choisi.
 *
 * Pas de mot de passe actuel demandé : la personne n'en a jamais eu.
 */
#[IsGranted('ROLE_USER')]
class ChoosePasswordController extends BaseController
{
    #[Route('/mon/mot-de-passe', name: 'password_choose')]
    public function choose(Request $request, UserPasswordHasherInterface $passwordHasher, EntityManagerInterface $entityManager, Security $security): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        // un compte avec un mot de passe choisi le change par "Mot de passe oublié"
        if (!$user->mustChoosePassword()) {
            return $this->redirectToRoute('dashboard');
        }

        $this->addBreadcrumb('Dashboard', 'dashboard');
        $this->addBreadcrumb('Mot de passe');

        $form = $this->createForm(ChangePasswordForm::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword($passwordHasher->hashPassword($user, $form->get('plainPassword')->getData()));
            $user->removeRole(User::ROLE_AUTOGENERATED_PASSWORD);

            $entityManager->flush();

            $this->addFlash('success', 'Votre mot de passe est enregistré.');

            // le mot de passe et les rôles ont changé : User::isEqualTo() déconnecterait la personne, on la reconnecte
            return $security->login($user, LoginFormAuthenticator::class);
        }

        return $this->render('account_area/password/choose.html.twig', [
            'form' => $form,
        ]);
    }
}
